services:
  verba:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .docker.env
    volumes:
      - ./data:/data/
    depends_on:
      weaviate:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Map Docker to local machine
    networks:
      - ollama-docker

  weaviate:
    image: semitechnologies/weaviate:1.25.10
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    ports:
      - "8080:8080"
      - "3000:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    env_file:
      - .env
    networks:
      - ollama-docker

volumes:
  weaviate_data: {}

networks:
  ollama-docker:
    external: false


  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "7869:11434"
  #   volumes:
  #     - ./ollama/ollama:/root/.ollama
  #   container_name: ollama
  #   pull_policy: always
  #   tty: true
  #   restart: always
  #   environment:
  #     - OLLAMA_KEEP_ALIVE=24h
  #     - OLLAMA_HOST=0.0.0.0
  #   networks:
  #     - ollama-docker
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 6G  # Maximum 6GB RAM for Ollama
  #         cpus: "3.0" # Maximum 3 CPU cores
  #       reservations:
  #         memory: 3G  # At least 3GB RAM allocated
  #         cpus: "1.5" # At least 1.5 CPU cores reserved