version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"  # Enable Docker provider for automatic service discovery
      - "--entryPoints.web.address=:80"  # HTTP entry point for all traffic
      - "--entryPoints.websecure.address=:443"  # HTTPS entry point (optional, requires certs)
      - "--providers.docker.network=ollama-docker"  # Use ollama-docker network
      - "--log.level=INFO"
    ports:
      - "80:80"    # HTTP Traffic
      - "443:443"  # HTTPS Traffic (Optional)
    networks:
      - ollama-docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # Allow Traefik to communicate with Docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"  # Dashboard access
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"

  verba:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .docker.env
    volumes:
      - ./data:/data/
    depends_on:
      weaviate:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - ollama-docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.verba.rule=Host(`verba.localhost`)"
      - "traefik.http.services.verba.loadbalancer.server.port=8000"

  weaviate:
    image: semitechnologies/weaviate:1.25.10
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    ports:
      - "8080:8080"
      - "3000:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    env_file:
      - .env
    networks:
      - ollama-docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weaviate.rule=Host(`weaviate.localhost`)"
      - "traefik.http.services.weaviate.loadbalancer.server.port=8080"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "7869:11434"
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.rule=Host(`ollama.localhost`)"
      - "traefik.http.services.ollama.loadbalancer.server.port=11434"

volumes:
  weaviate_data: {}

networks:
  ollama-docker:
    external: false
